### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by ruippgoncalves** [adobe-research/ActionScript4#4]
In the white papers it talks about the new features that were comming to AS4, and shows us a bit of how the API was going to be. I am wondering if all the API was ever published or can be published, like the https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/ for AS3 or a playerglobal.swc in a way.

**Comment by phohensee** [comment]
Unfortunately, no. What's posted is all there is. Adobe canceled the project in mid-2013 when they decided to put Flash into maintenance mode.
